services:
    oc_platform.email.application_mailer:
        class: OC\PlatformBundle\Email\ApplicationMailer
        arguments:
            - "@mailer"

    oc_platform.doctrine_listener.application_creation:
        class: OC\PlatformBundle\DoctrineListener\ApplicationCreationListener
        arguments:
            - "@oc_platform.email.application_mailer"
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    oc_platform.purge:
        class: OC\PlatformBundle\Purge\PurgerAdvert
        arguments:
            - "@doctrine.orm.entity_manager"

    oc_platform.antispam:
        class: OC\PlatformBundle\Antispam\OCAntispam
        arguments:
            - "@mailer"
            - %locale%
            - 50


