core_homepage:
    path:     /
    defaults: { _controller: CoreBundle:Core:index } # nom du bundle:nom du controller:nom de la function dans le controller


core_contact:
    path:     /contact
    defaults: { _controller: CoreBundle:Core:contact} # nom du bundle:nom du controller:nom de la function dans le controller


